openapi: "3.0.0"
info:
  title: CHALLENGE BACKEND - NodeJs
  version: "1.2"
  description: API para explorar el mundo de Disney

servers:
  - url: http://localhost:8080

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only

security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      tags:
        - Users Login
      summary: Create user
      description: Allows create users
      responses:
        "201":
          description: User created
        "400":
          description: Internal error
          content:
            application/json:
              schema:
                type: object
                example: {'message': Error'}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: namesa
                  example: Sophi
                lastname:
                  type: string
                  description: Lastname
                  example: Olivera
                email:
                  type: string
                  description: Email
                  example: sophia@nothing.com
                password:
                  type: string
                  description: Password
                  example: 1234
                repeatPassword:
                  type: string
                  description: Confirm password
                  example: 1234

  /auth/login:
    post:
      tags:
        - Users Login
      summary: User login
      description: Login of the users
      responses:
        "201":
          description: User loged
        "400":
          description: Incorrect information
          content:
            application/json:
              schema:
                type: object
                example: {'message': Credentials error'}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email
                  example: sophia@nothing.com
                password:
                  type: string
                  description: Password
                  example: 1234

  /allCharacters:
    get:
      tags:
        - Characters 
      summary: Get all Characters
      description: Allows users get all the Characters
      responses:
          "200":
            description: Shows Characters
          "400":
            description: Error
            content:
              application/json:
                schema:
                  type: object
                  example: {'message': Credentials error'}
        
  /createCharacter:
    post:
      tags:
        - Characters 
      summary: Add character
      description: Allows create a character
      responses:
          "200":
            description: Add character
            content:
              application/json:
                schema:
                  type: object
                  example: {'message': Character Created}
          "400":
            description: Error
            content:
              application/json:
                schema:
                  type: object
                  example: {'message': Credentials error'}

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  description: Image URL
                  example: https://imgur.com/a/MoX4MVJ
                name:
                  type: string
                  description: Character name
                  example: Buzz Lightyear
                age:
                  type: integer
                  description: Character age
                  example: 22
                weight:
                  type: string
                  description: Character weight
                  example: 1kg
                